---
# tasks file for aws_codedeploy
#
- name: Install codedeploy agent package
  apt:
    deb: "https://s3.amazonaws.com/aws-codedeploy-us-east-1/latest/codedeploy-agent_all.deb"
    state: present
    update_cache: no
  become: yes

